name: Build and Deploy CV


on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest 
    steps:
      - name: 'check'
        uses: actions/checkout@v2
      - name: 'buildpdf'
        run: |
          sudo docker build --tag my_container -f Dockerfile .
          sudo docker run --name=latex my_container
          sudo docker start latex
          sudo docker cp latex:./cv.pdf cv.pdf
      - name: 'check'
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: ./cv.pdf
