name: Build and Deploy CV

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Build PDF'
        run: |
          docker build --tag my_container .
          docker run --name latex my_container
          docker cp latex:./cv.pdf cv.pdf
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: cv.pdf

