name: Build and Deploy CV

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
      - name: 'Build PDF'
        run: |
          sudo docker build --tag my_container -f Dockerfile .
          sudo docker run --name=latex my_container
          sudo docker cp latex:/cv.pdf cv.pdf 
      - name: 'Upload PDF'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./cv.pdf
          runs-on: ubuntu-latest
          
  deploy:
    # Add a dependency to the build job
    needs: docker

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: artifacts


        
      
