name: cv_create

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t cv-builder .

      - name: Run Docker container
        run: docker run --name cv_container -v ${{ github.workspace }}/output:/output cv-builder

      - name: List output directory
        run: ls ${{ github.workspace }}/output

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: output/
