name: Build and Deploy CV

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
      - name: 'Build PDF'
        run: |
          sudo docker build --tag my_container -f Dockerfile .
          sudo docker run --name=latex my_container
          sudo docker cp latex:/cv.pdf cv.pdf 
      - name: 'Upload PDF'
        uses: actions/upload-artifact@v2
        with:
          name: artefact
          path: ./cv.pdf
          runs-on: ubuntu-latest

  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
  
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artefact
          path: ./cv.pdf
    
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git switch artifacts
          git add cv.pdf
          git commit -m "Update CV PDF"
          git push

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: artifacts
          folder: .  
 
